search:

    1
filter:

    2

actions:




sql:

    SELECT * FROM users LIMIT 10

listing:
    -
        header:
            label: Id
            sort: s.id
            width: 40

        body:
            type: text
            align: center
            row: id
    -
        header:
            label: Name
            sort: s.name
            width: 100

        body:
            align: left
            row: name

    -
        header:
            custom: { class: custom, action: header}

        body:
            custom: { class: custom, action: body}
            align: left

    -
        header:
            label: Actions

        body:
            align: center
            row: test
            type: add|edit|delete


form:
