search:

    1
filter:

    2

actions:




sql:

    SELECT * FROM users LIMIT 10

listing:
    -
        header:
            label: Id
            sort: s.id
            width: 40

        body:
            type: text
            row: id
    -
        header:
            label: Name
            sort: s.name
            width: 100

        body:
            row: name

    -
        header:
            label: Actions
        body:
            row: test
            type: add|edit|delete


form:
