query:
    search: [name]
    total: count(*)
    select: '*'
    from: users
    where: 1
    group: 1
    order: asc
    limit: 10

filters:
    -
        type: select
        attributes:
            name: status
            options: { '': 'Select Status', active: Active, inactive: Inactive}
            selected: active
    -
        custom: { class: custom, action: filter }

listing:
    -
        header:
            label: Id
            sort: s.id
            width: 40

        body:
            type: text
            align: center
            row: id
    -
        header:
            label: Name
            sort: s.name
            width: 100

        body:
            align: left
            row: name

    -
        header:
            custom: { class: custom, action: header }

        body:
            custom: { class: custom, action: body}
            align: left

    -
        header:
            label: Actions

        body:
            align: center
            actions: { delete: true, edit: true }

form:
