search:

    1
filter:

    2

actions:




sql:

    SELECT * FROM sample

listing:
    -
        header:
            label: Id
            sort: s.id
            width: 40

        data:
            type: text
            row: s.id
    -
        header:
            label: Id
            sort: s.status
            width: 100

        data:
            row: s.status
form:
